from flask import Flask, render_template, request, jsonify, send_file, redirect, url_for, session
import pandas as pd
from functools import wraps
import webbrowser
from threading import Timer
import json
import os
from notification_service import check_new_tickets
from apscheduler.schedulers.background import BackgroundScheduler
import time
import gspread
from google.oauth2.service_account import Credentials
from pandasql import sqldf
from datetime import datetime , timedelta
import random
from customer_ai import process_customer_ai
import customer_ai
from werkzeug.utils import secure_filename
from db import (
    init_db,
    get_all,
    insert_row,
    delete_by_lead_id,
    find_by_lead_id,
    find_by_customer_id,
    update_by_customer_id,
    count_rows,
    ONBOARDING_COLUMNS,
    PAYMENT_FOLLOW_UP_COLUMNS,
    delete_by_customer_id,
    SUPPORT_TASKS_COLUMNS,
    COMMUNICATIONS_COLUMNS,
    insert,
    update,
    find_by_lead_id_all,
    update_communications_by_lead_id,
    mark_messages_read_by_lead_id,
    DATA_OPERATIONS_COLUMNS,
    get_next_numeric_id,
    select,
    select_one
)




 
app = Flask(__name__)

init_db()

cached_df = None
last_load = 0

# if os.environ.get(
#     "WERKZEUG_RUN_MAIN"
# ) == "true":


scheduler = BackgroundScheduler()



PLAN_CONFIG = {

    "starter": {
        "price": 49,
        "months": 1
    },

    "premium": {
        "price": 149,
        "months": 3
    },

    "business": {
        "price": 299,
        "months": 6
    },

    "enterprise": {
        "price": 599,
        "months": 12
    }

}



app.secret_key = "bytedata_secure_session_key"

SCOPES = [

    "https://www.googleapis.com/auth/spreadsheets",

    "https://www.googleapis.com/auth/drive"

]

creds = Credentials.from_service_account_file(

    # "credentials.json",

    "/etc/secrets/credentials.json",

    scopes=SCOPES

)

gc = gspread.authorize(
    creds
)


def get_support_tasks_sheet():

    spreadsheet = gc.open_by_key(
        "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
    )

    return spreadsheet.worksheet("Support_Tasks")

#logic for lead core logic 

     
def process_leads():

    try:

        print("PROCESSING LEADS...")

        spreadsheet = gc.open_by_key(
            "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
        )

        leads_sheet = spreadsheet.worksheet("Leads")

        leads = leads_sheet.get_all_records()

        for lead in leads:

            processed = str(
                lead.get("scheduler_processed", "")
            ).strip().lower()

            status = str(
                lead.get("lead_status", "")
            ).strip().lower()

            if processed == "yes" or status != "new":
                continue

            random_number = random.randint(1, 100)

            lead_id = str(lead.get("lead_id", ""))

            company_name = lead.get("company_name", "")
            contact_person = lead.get("contact_person", "")
            email = lead.get("email", "")
            phone = lead.get("phone", "")
            country = lead.get("country", "")

            plan = str(
                lead.get("plan_interested", "starter")
            ).lower()

            plan_data = PLAN_CONFIG.get(
                plan,
                PLAN_CONFIG["starter"]
            )

            if random_number <= 70:

                insert_row(
                    "payment_follow_up",
                    PAYMENT_FOLLOW_UP_COLUMNS,
                    {
                        "lead_id": lead_id,
                        "company_name": company_name,
                        "contact_person": contact_person,
                        "email": email,
                        "phone": phone,
                        "plan_interested": plan,
                        "payment_referer": f"PAY-{lead_id}",
                        "payment_link": f"https://pay.bytedata.app/{lead_id}",
                        "payment_status": "Pending",
                        "attempt_count": "1",
                        "assigned_to": "admin",
                        "last_contact_date": datetime.now().strftime("%Y-%m-%d"),
                        "issue_type": random.choice([
                            "Card Declined",
                            "Payment Pending",
                            "Customer Not Responding",
                            "Payment Link Expired"
                        ]),
                        "notes": "Auto generated by scheduler",
                        "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    }
                )

                new_status = "Payment Pending"

            else:

                payment_date = datetime.now()

                expiry_date = payment_date + timedelta(
                    days=plan_data["months"] * 30
                )

                customer_id = (
                    "CUST" +
                    str(count_rows("onboarding") + 1).zfill(3)
                )

                insert_row(
                    "onboarding",
                    ONBOARDING_COLUMNS,
                    {
                        "customer_id": customer_id,
                        "company_name": company_name,
                        "contact_person": contact_person,
                        "email": email,
                        "phone": phone,
                        "country": country,
                        "subscription_plan": plan.title(),
                        "subscription_amount": plan_data["price"],
                        "currency": "USD",
                        "status": "Active",
                        "next_payment_date": expiry_date.strftime("%Y-%m-%d"),
                        "days_overdue": "0",
                        "payment_link": f"https://pay.bytedata.app/{customer_id}",
                        "last_contact_date": "",
                        "last_message": "Auto onboarded by scheduler",
                        "notes": "Lead converted successfully",
                        "assigned_to": "admin",
                        "payment_date": payment_date.strftime("%Y-%m-%d"),
                        "expiry_date": expiry_date.strftime("%Y-%m-%d"),
                        "days_remaining": str((expiry_date - payment_date).days),
                        "subscription_duration": str(plan_data["months"]),
                        "auto_status": "Active",
                        "renewal_amount": str(plan_data["price"]),
                        "payment_stage": "Paid",
                        "payment_link_status": "Sent",
                        "payment_sent_date": payment_date.strftime("%Y-%m-%d"),
                        "payment_received_date": payment_date.strftime("%Y-%m-%d"),
                        "migration_status": "Completed",
                        "migration_date": payment_date.strftime("%Y-%m-%d"),
                        "payment_reference": f"PAY-{customer_id}",
                        "lead_id": lead_id,
                        "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        "renewal_followup_created": "No",
                        "last_renewal_date": ""
                    }
                )

                new_status = "Paid"

            all_rows = leads_sheet.get_all_values()

            headers = all_rows[0]

            scheduler_col = headers.index("scheduler_processed") + 1
            status_col = headers.index("lead_status") + 1

            for row_num, row in enumerate(all_rows[1:], start=2):

                if str(row[0]).strip() == lead_id:

                    leads_sheet.update_cell(
                        row_num,
                        scheduler_col,
                        "Yes"
                    )

                    leads_sheet.update_cell(
                        row_num,
                        status_col,
                        new_status
                    )

                    break

            print(f"{lead_id} -> {new_status}")

    except Exception as e:

        print("LEAD PROCESS ERROR:", e)

def process_customer_renewals():

    try:

        print("CHECKING CUSTOMER RENEWALS...")

        records = get_all("onboarding")

        today = datetime.now().date()

        for row in records:

            customer_id = str(row.get("customer_id", "")).strip()

            expiry_date = str(row.get("expiry_date", "")).strip()

            if not customer_id or not expiry_date:
                continue

            expiry = datetime.strptime(
                expiry_date,
                "%Y-%m-%d"
            ).date()

            days_remaining = (expiry - today).days

            updates = {
                "days_remaining": str(days_remaining)
            }

            if days_remaining < 0:

                updates["days_overdue"] = str(abs(days_remaining))
                updates["status"] = "Overdue"
                updates["auto_status"] = "Overdue"

                renewal_created = str(
                    row.get("renewal_followup_created", "")
                ).strip().lower()

                if renewal_created != "yes":

                    renewal_lead_id = "RENEW-" + customer_id

                    existing_followup = find_by_lead_id(
                        "payment_follow_up",
                        renewal_lead_id
                    )

                    if not existing_followup:

                        insert_row(
                            "payment_follow_up",
                            PAYMENT_FOLLOW_UP_COLUMNS,
                            {
                                "lead_id": renewal_lead_id,
                                "company_name": row.get("company_name", ""),
                                "contact_person": row.get("contact_person", ""),
                                "email": row.get("email", ""),
                                "phone": row.get("phone", ""),
                                "plan_interested": row.get("subscription_plan", ""),
                                "payment_referer": "RENEWAL",
                                "payment_link": row.get("payment_link", ""),
                                "payment_status": "Pending",
                                "attempt_count": "1",
                                "assigned_to": row.get("assigned_to", "admin"),
                                "last_contact_date": datetime.now().strftime("%Y-%m-%d"),
                                "issue_type": "Renewal Due",
                                "notes": "Auto renewal follow up",
                                "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            }
                        )

                    updates["renewal_followup_created"] = "Yes"

            elif days_remaining <= 7:

                updates["days_overdue"] = "0"
                updates["status"] = "Due Soon"
                updates["auto_status"] = "Due Soon"

            else:

                updates["days_overdue"] = "0"
                updates["status"] = "Active"
                updates["auto_status"] = "Active"

            update_by_customer_id(
                "onboarding",
                customer_id,
                updates
            )

        print("CUSTOMER RENEWAL CHECK FINISHED")

    except Exception as e:

        print("RENEWAL ERROR:", e)



def get_customer_ai_sheet():

    spreadsheet = gc.open_by_key(
        "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
    )

    return spreadsheet.worksheet("CustomerAI")

def get_onboarding_sheet():

    class SQLiteOnboardingSheet:

        def get_all_records(self):
            return get_all("onboarding")

    return SQLiteOnboardingSheet()

def get_communications_sheet():

    class SQLiteCommunicationsSheet:

        def get_all_records(self):
            return get_all("communications")

        def append_row(self, values):
            data = {}

            for index, col in enumerate(COMMUNICATIONS_COLUMNS):
                data[col] = values[index] if index < len(values) else ""

            insert(
                "communications",
                data
            )

    return SQLiteCommunicationsSheet()

customer_ai.initialize(
    get_customer_ai_sheet,
    get_onboarding_sheet,
    get_communications_sheet
)

scheduler.add_job(
    check_new_tickets,
    "interval",
    hours=8,
    id="check_new_tickets",
    replace_existing=True
)

scheduler.add_job(
    process_leads,
    "interval",
    hours=1,
    id="process_leads",
    replace_existing=True
)

scheduler.add_job(
    process_customer_renewals,
    "interval",
    hours=6,
    id="process_customer_renewals",
    replace_existing=True,
    next_run_time=datetime.now()
)

scheduler.add_job(
    customer_ai.process_customer_ai,
    "interval",
    minutes=10,
    id="customer_ai",
    replace_existing=True
)


if not scheduler.running:
    scheduler.start()
    print("Scheduler Started")





all_data = []

PROGRESS_FILE = "progress.json"


app.secret_key = "bytedata_secure_session_key"



def is_admin():
    return session.get("role") == "admin"



def get_sheet_data():

    global cached_df
    global last_load

    current_time = time.time()

    if (
        cached_df is None
        or
        current_time - last_load > 60
    ):

        print(
            "Refreshing Sheet..."
        )

        cached_df = pd.read_csv(
            GOOGLE_SHEET_CSV
        )

        cached_df.columns = (
            cached_df.columns
            .str.lower()
        )

        last_load = current_time

    return cached_df

def get_main_sheet():

    spreadsheet = gc.open_by_key(

        "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"

    )

    worksheet = spreadsheet.worksheet("Sheet1")

    return worksheet

def get_followup_sheet():

    spreadsheet = gc.open_by_key(
        "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
    )

    return spreadsheet.worksheet("Payment_Follow_Up")



def load_progress():

    if not os.path.exists(PROGRESS_FILE):
        return {}

    try:

        with open(PROGRESS_FILE, "r") as f:
            return json.load(f)

    except:
        return {}


def save_progress(progress_data):

    with open(PROGRESS_FILE, "w") as f:
        json.dump(progress_data, f)



 
# =====================================
# VERIFIED DATA
# =====================================

all_data = []

# =====================================
# SHEETS
# =====================================

GOOGLE_SHEET_CSV = "https://docs.google.com/spreadsheets/d/1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/export?format=csv"

LOGIN_SHEET_CSV = "https://docs.google.com/spreadsheets/d/1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/export?format=csv&gid=265750894"

CUSTOMERS_SHEET_CSV = (
    "https://docs.google.com/spreadsheets/d/"
    "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/"
    "export?format=csv&gid=501341251"
)

COMMUNICATIONS_SHEET_CSV = (
    "https://docs.google.com/spreadsheets/d/"
    "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/"
    "export?format=csv&gid=1403813074"
)

PAYMENTS_SHEET_CSV = (
    "https://docs.google.com/spreadsheets/d/"
    "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/"
    "export?format=csv&gid=755595798"
)

PAYMENT_FOLLOWUP_CSV = (
    "https://docs.google.com/spreadsheets/d/1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM/edit?gid=336204039#gid=336204039"
)


# print(PAYMENT_FOLLOWUP_CSV)





def get_notes_sheet():

    spreadsheet = gc.open_by_key(
        "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
    )

    return spreadsheet.worksheet(
        "CommunicationNotes"
    )


# =====================================
# LOGIN REQUIRED
# =====================================

def login_required(f):

    @wraps(f)

    def decorated_function(*args, **kwargs):

        if not session.get("logged_in"):

            return redirect(
                url_for("login_page")
            )

        return f(*args, **kwargs)

    return decorated_function

# =====================================
# LOGIN PAGE
# =====================================

@app.route("/login")
def login_page():

    return render_template(
        "login_v2.html"
    )

# =====================================
# LOGIN USER
# =====================================

@app.route("/login-user", methods=["POST"])
def login_user():

    try:

        username = request.json.get(
            "username"
        )

        password = request.json.get(
            "password"
        )

        df = pd.read_csv(
            LOGIN_SHEET_CSV
        )

        df.columns = df.columns.str.lower()

        user_row = df[
            (df["user"].astype(str).str.lower() == str(username).lower()) &
            (df["pass"].astype(str) == str(password))
        ]

        if len(user_row) > 0:

            # session["logged_in"] = True

            # session["username"] = username.lower()

            # # RESET POINTER

            # session["current_index"] = 0
            role = str(
                user_row.iloc[0]["role"]
            ).lower()
            session["logged_in"] = True

            session["username"] = username.lower()
            session["role"] = role.lower()

            progress = load_progress()

            session["current_index"] = progress.get(
                username.lower(),
                0
            )

            return jsonify({

                "status":"success",
                "message":"Login Successful",
                "redirect": "/dashboard"

            })

        return jsonify({

            "status":"error",

            "message":"Invalid Login"

        })

    except Exception as e:

        return jsonify({

            "status":"error",

            "message":str(e)

        })

# =====================================
# HOME
# =====================================

@app.route("/")
@login_required
def home():


    return render_template(
        "indexv2.html",
        role=session.get("role"),
        username=session.get("username")


    )

# =====================================
# DASHBOARD
# =====================================

@app.route("/dashboard")
@login_required
def dashboard():
     

    # return """
    # <h1 style='color:red'>
    # DASHBOARD ROUTE TEST
    # </h1>
    # """

    return render_template(
        "dashboard_v3.html",
         role=session.get("role")

    )




@app.route("/operations")
@login_required
def operations():



    if session.get("role") != "admin":
        return redirect("/dashboard")

    
    return render_template(
        "operationsv2.html",
        role=session.get("role")    )

@app.route("/operations-data")
@login_required
def operations_data():

    try:

        # sheet = get_followup_sheet()

        # records = sheet.get_all_records()

        records = get_all("payment_follow_up")

        df = pd.DataFrame(records)

        # df.columns = (
        #     df.columns
        #     .str.lower()
        #     .str.strip()
        # )

        df.columns = [
            str(col).lower().strip()
            for col in df.columns
        ]

        df = df.fillna("")

        customers = []

        for _, row in df.iterrows():

            customers.append({

                "lead_id":
                    row.get(
                        "lead_id",
                        ""
                    ),

                "company_name":
                    row.get(
                        "company_name",
                        ""
                    ),

                "plan":
                    row.get(
                        "plan_interested",
                        ""
                    ),

                "issue_type":
                    row.get(
                        "issue_type",
                        ""
                    ),

                "payment_status":
                    row.get(
                        "payment_status",
                        ""
                    ),

                "assigned_to":
                    row.get(
                        "assigned_to",
                        ""
                    ),

                "last_contact":
                    row.get(
                        "last_contact_date",
                        ""
                    ),

                "payment_link":
                    row.get(
                        "payment_link",
                        ""
                    ),

                "payment_reference":
                    row.get(
                        "payment_reference",
                        ""
                    ),

                "email":
                    row.get(
                        "email",
                        ""
                    ),

                "phone":
                    row.get(
                        "phone",
                        ""
                    ),

                "notes":
                    row.get(
                        "notes",
                        ""
                    )

            })

             
             

        return jsonify(
            customers
        )

    except Exception as e:

        return jsonify({

            "error":
                str(e)

        })



@app.route("/mark-paid", methods=["POST"])
@login_required
def mark_paid():

    try:

        lead_id = str(
            request.json.get("lead_id", "")
        ).strip()

        if not lead_id:

            return jsonify({
                "status": "error",
                "message": "Missing lead_id"
            })

        is_renewal = lead_id.startswith("RENEW-")

        spreadsheet = gc.open_by_key(
            "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
        )

        leads_sheet = spreadsheet.worksheet("Leads")
        leads = leads_sheet.get_all_records()

        followups = get_all("payment_follow_up")
        onboarding = get_all("onboarding")

        target = None

        for row in followups:

            if str(row.get("lead_id", "")).strip() == lead_id:

                target = row
                break

        if not target:

            return jsonify({
                "status": "error",
                "message": "Lead not found in payment follow up"
            })

        country = ""

        original_lead_id = lead_id

        if is_renewal:

            original_lead_id = ""

        for lead in leads:

            if str(lead.get("lead_id", "")).strip() == original_lead_id:

                country = lead.get("country", "")
                break

        payment_date = datetime.now()

        if is_renewal:

            customer_id = lead_id.replace("RENEW-", "")

            customer = find_by_customer_id(
                "onboarding",
                customer_id
            )

            if not customer:

                return jsonify({
                    "status": "error",
                    "message": "Renewal customer not found in onboarding"
                })

            plan = str(
                customer.get("subscription_plan", "starter")
            ).lower()

            plan_data = PLAN_CONFIG.get(
                plan,
                PLAN_CONFIG["starter"]
            )

            expiry_date = payment_date + timedelta(
                days=plan_data["months"] * 30
            )

            update_by_customer_id(
                "onboarding",
                customer_id,
                {
                    "payment_date": payment_date.strftime("%Y-%m-%d"),
                    "expiry_date": expiry_date.strftime("%Y-%m-%d"),
                    "next_payment_date": expiry_date.strftime("%Y-%m-%d"),
                    "status": "Active",
                    "auto_status": "Active",
                    "days_remaining": str((expiry_date - payment_date).days),
                    "days_overdue": "0",
                    "renewal_followup_created": "No",
                    "last_renewal_date": payment_date.strftime("%Y-%m-%d"),
                    "payment_reference": target.get("payment_reference", ""),
                    "payment_stage": "Paid",
                    "payment_received_date": payment_date.strftime("%Y-%m-%d")
                }
            )

            delete_by_lead_id(
                "payment_follow_up",
                lead_id
            )

            return jsonify({
                "status": "success"
            })

        for customer in onboarding:

            if str(customer.get("lead_id", "")).strip() == lead_id:

                return jsonify({
                    "status": "error",
                    "message": "Lead already onboarded"
                })

        plan = str(
            target.get("plan_interested", "starter")
        ).lower()

        plan_data = PLAN_CONFIG.get(
            plan,
            PLAN_CONFIG["starter"]
        )

        expiry_date = payment_date + timedelta(
            days=plan_data["months"] * 30
        )

        customer_id = (
            "CUST" +
            str(count_rows("onboarding") + 1).zfill(3)
        )

        insert_row(
            "onboarding",
            ONBOARDING_COLUMNS,
            {
                "customer_id": customer_id,
                "company_name": target.get("company_name", ""),
                "contact_person": target.get("contact_person", ""),
                "email": target.get("email", ""),
                "phone": target.get("phone", ""),
                "country": country,
                "subscription_plan": plan.title(),
                "subscription_amount": str(plan_data["price"]),
                "currency": "USD",
                "status": "Active",
                "next_payment_date": expiry_date.strftime("%Y-%m-%d"),
                "days_overdue": "0",
                "payment_link": target.get("payment_link", ""),
                "last_contact_date": "",
                "last_message": "Payment confirmed by support",
                "notes": "Converted from Payment Follow Up",
                "assigned_to": target.get("assigned_to", "admin"),
                "payment_date": payment_date.strftime("%Y-%m-%d"),
                "expiry_date": expiry_date.strftime("%Y-%m-%d"),
                "days_remaining": str((expiry_date - payment_date).days),
                "subscription_duration": str(plan_data["months"]),
                "auto_status": "Active",
                "renewal_amount": str(plan_data["price"]),
                "payment_stage": "Paid",
                "payment_link_status": "Sent",
                "payment_sent_date": payment_date.strftime("%Y-%m-%d"),
                "payment_received_date": payment_date.strftime("%Y-%m-%d"),
                "migration_status": "Completed",
                "migration_date": payment_date.strftime("%Y-%m-%d"),
                "payment_reference": target.get("payment_reference", ""),
                "lead_id": lead_id,
                "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "renewal_followup_created": "No",
                "last_renewal_date": ""
            }
        )

        delete_by_lead_id(
            "payment_follow_up",
            lead_id
        )

        return jsonify({
            "status": "success"
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })

@app.route("/communications")
@login_required
def communications():

    if session.get("role") != "admin":
        return redirect("/dashboard")
    
    return render_template("communicationsv3.html" , role=session.get("role")
)    



@app.route("/communications-data")
@login_required
def communications_data():

    try:

        df = pd.read_csv(
            COMMUNICATIONS_SHEET_CSV
        )

        df.columns = (
            df.columns
            .str.lower()
            .str.strip()
        )

        df = df.fillna("")

        # df = df[
        #     df["status"]
        #     .astype(str)
        #     .str.lower()
        #     != "closed"
        # ]

        messages = df.to_dict(
            orient="records"
        )

        # try:
        #     check_new_tickets()
        # except Exception as e:
        #      print(
        #     "Notification Error:",
        #     e
        # )

        return jsonify(
            messages
        )

    except Exception as e:

        return jsonify({

            "error": str(e)

        })


# =====================================
# CUSTOMERS PAGE
# =====================================

@app.route("/customers")
@login_required
def customers():

    if session.get("role") != "admin":
        return redirect("/dashboard")


    return render_template(
        "customersv2.html",
        role=session.get("role")
    )

# =====================================
# CUSTOMERS DATA API
# =====================================

@app.route("/customers-data")
@login_required
def customers_data():

    try:

        df = pd.read_csv(
            CUSTOMERS_SHEET_CSV
        )

        df.columns = (
            df.columns
            .str.lower()
            .str.strip()
        )

        df = df.fillna("")

        customers = df.to_dict(
            orient="records"
        )

        return jsonify(
            customers
        )

    except Exception as e:

        return jsonify({

            "error":
                str(e)

        })

# =====================================
# DASHBOARD DATA
# =====================================

@app.route("/dashboard-data")
@login_required
def dashboard_data():

    try:

        # df = pd.read_csv(
        #     CUSTOMERS_SHEET_CSV
        # )
        # onboarding = get_onboarding_sheet().get_all_records()
        onboarding = get_all("onboarding")        

        df = pd.DataFrame(onboarding)

        df.columns = (
            df.columns
            .str.lower()
            .str.strip()
        )

        total_customers = len(df)

        active_customers = len(

            df[
                df["status"]
                .astype(str)
                .str.lower()
                == "active"
            ]

        )

        today = datetime.now().strftime("%Y-%m-%d")

        due_today = len(

            df[
                df["next_payment_date"]
                .astype(str)
                == today
            ]

        )

        overdue_customers = len(

        df[
            df["auto_status"]
            .astype(str)
            .str.lower()
            == "overdue"
        ]

        )

        active_df = df[
                    df["status"]
                .astype(str)
                .str.lower()
                == "active"
            ]

        total_revenue = (

         

            
                pd.to_numeric(
                    active_df["subscription_amount"],
                    errors="coerce"
                )
                .fillna(0)
                .sum()
        

        )

        customers = (
            df.head(10)
            .fillna("")
            .to_dict(
                orient="records"
            )
        )

        return jsonify({

            "total_customers":
                int(
                    total_customers
                ),

            "active_customers":
                int(
                    active_customers
                ),

            "due_today":
                int(
                    due_today
                ),

            "overdue_customers":
                int(
                    overdue_customers
                ),

            "total_revenue":
                float(
                    total_revenue
                ),

            "customers":
                customers

        })

    except Exception as e:

        return jsonify({

            "error":
                str(e)

        })




@app.route("/dashboard-analytics")
@login_required
def dashboard_analytics():

    df = pd.read_csv(
        CUSTOMERS_SHEET_CSV
    )

    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
    )

    return jsonify({

        "countries":
            df["country"]
            .value_counts()
            .to_dict(),

        "assigned":
            df["assigned_to"]
            .value_counts()
            .to_dict(),

        "status":
            df["status"]
            .value_counts()
            .to_dict()

    })



@app.route("/analytics")
@login_required
def analytics():
    return render_template(
        "analytics.html"
    )


@app.route("/reports")
@login_required
def reports():
    return render_template(
        "reports.html"
    )


@app.route("/settings")
@login_required
def settings():
    return render_template(
        "settings.html"
    )



# =====================================
# FETCH NEXT ROW
# =====================================

# @app.route("/fetch-next-row")
# @login_required
# def fetch_next_row():

#     try:

#         logged_user = session.get(
#             "username",
#         ).lower()

#         # df = pd.read_csv(
#         #     GOOGLE_SHEET_CSV
#         # )

#         global cached_df
#         cached_df = None

#         df = get_sheet_data()

#         df.columns = df.columns.str.lower()

#         print("USER:", logged_user)

#         print(
#             df[["assign", "verified"]]
#             .head(20)
#         )

#         print(df.columns.tolist())


#         # FILTER USER ROWS

#         user_rows = df[
#             df["assign"].astype(str).str.lower() == logged_user
#         ]

#         user_rows = user_rows.fillna("")

#         # GET POINTER

#         user_rows = user_rows[
#         user_rows["verified"]
#         .astype(str)
#         .str.strip()
#         .str.lower()
#         == "secured"
#         ]

#         print("ROWS FOUND:", len(user_rows))


#         if len(user_rows) == 0:

#             return jsonify({
#                 "status": "finished",
#                 "message": "No More Rows"
#             })
        
#         row = user_rows.iloc[0].to_dict()

#         return jsonify({

#             "status":"success",

#             "row":row

#         })

#     except Exception as e:

#         return jsonify({

#             "status":"error",

#             "message":str(e)

#         })

@app.route("/fetch-next-row")
@login_required
def fetch_next_row():

    try:

        logged_user = session.get("username", "").lower()

        row = select_one(
            "data_operations",
            """
            lower(assign) = ?
            AND lower(verified) IN ('secured', 'no', '')
            """,
            [logged_user],
            order_by="CAST(id AS INTEGER) ASC"
        )

        if not row:

            return jsonify({
                "status": "finished",
                "message": "No More Assigned Rows"
            })

        return jsonify({
            "status": "success",
            "row": row
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })





# =====================================
# SAVE VERIFIED
# =====================================

# @app.route("/save-verified", methods=["POST"])
# @login_required
# def save_verified():

#     try:

#         data = request.json

#         data["verified_by"] = session.get(
#             "username"
#         )

#         all_data.append(
#             data
#         )

#         return jsonify({

#             "status":"success"

#         })

#     except Exception as e:

#         return jsonify({

#             "status":"error",

#             "message":str(e)

#         })

# # =====================================
# # EXPORT
# # =====================================

# @app.route("/export-excel")
# @login_required
# def export_excel():

#     logged_user = session.get(
#         "username"
#     )

#     export_rows = []

#     for row in all_data:

#         if row.get(
#             "verified_by"
#         ) == logged_user:

#             export_rows.append(
#                 row
#             )

#     if len(export_rows) == 0:

#         return "No Verified Data"

#     df = pd.DataFrame(
#         export_rows
#     )

#     file_name = f"{logged_user}_verified.xlsx"

#     df.to_excel(

#         file_name,

#         index=False
#     )

#     return send_file(

#         file_name,

#         as_attachment=True
#     )

@app.route("/save-verified", methods=["POST"])
@login_required
def save_verified():

    try:

        data = request.json

        row_id = str(data.get("id", "")).strip()

        if not row_id:

            return jsonify({
                "status": "error",
                "message": "Missing row id"
            })

        updates = {}

        for col in DATA_OPERATIONS_COLUMNS:

            if col == "id":
                continue

            if col in data:
                updates[col] = str(data.get(col, ""))

        updates["verified"] = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        update(
            "data_operations",
            updates,
            "id = ?",
            [row_id]
        )

        return jsonify({
            "status": "success"
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })


@app.route("/payments")
@login_required
def payments():


    if session.get("role") != "admin":
        return redirect("/dashboard")
    
    return render_template(
        "payments.html",
        role=session.get("role")

    )

payments_cache = None
payments_cache_time = 0

def get_payments_data():

    global payments_cache
    global payments_cache_time

    now = time.time()

    if (
        payments_cache is None
        or
        now - payments_cache_time > 60
    ):

        payments_cache = pd.read_csv(
            PAYMENTS_SHEET_CSV
        )

        payments_cache.columns = (
            payments_cache.columns
            .str.lower()
            .str.strip()
        )

        payments_cache = payments_cache.fillna("")

        payments_cache_time = now

    return payments_cache

@app.route("/payments-data")
@login_required
def payments_data():

    df = pd.read_csv(PAYMENTS_SHEET_CSV)

    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
    )

    df = df.fillna("")

    return jsonify(
        df.to_dict(
            orient="records"
        )
    )

# @app.route(
#     "/update-sheet-row",
#     methods=["POST"]
# )
# @login_required
# def update_sheet_row():

#     try:

#         data = request.json

#         data["verified"] = datetime.now().strftime(
#             "%Y-%m-%d %H:%M:%S"
#         )

#         row_id = str(
#             data.get("id")
#         )

   

#         sheet = get_main_sheet()

#         records = sheet.get_all_records()

#         target_row = None

#         for index, row in enumerate(records):

#             if str(row.get("id")) == row_id:

#                 target_row = index + 2

#                 break

#         if not target_row:

#             return jsonify({

#                 "status":"error",

#                 "message":"Row not found"

#             })

#         headers = sheet.row_values(1)

#         updates = []

#         for col_index, header in enumerate(headers):

#             value = data.get(
#                 header,
#                 ""
#             )

#             updates.append({
#                 "range":
#                     gspread.utils.rowcol_to_a1(
#                         target_row,
#                         col_index + 1
#                     ),
#                 "values":
#                     [[str(value)]]
#             })

#         sheet.batch_update(updates)
#         global cached_df
#         cached_df = None
#         return jsonify({

#             "status":"success"

#         })

#     except Exception as e:

#         return jsonify({

#             "status":"error",

#             "message":str(e)

#         })
    

@app.route("/update-sheet-row", methods=["POST"])
@login_required
def update_sheet_row():

    try:

        data = request.json

        row_id = str(data.get("id", "")).strip()

        if not row_id:

            return jsonify({
                "status": "error",
                "message": "Missing row id"
            })

        allowed_updates = {}

        for col in DATA_OPERATIONS_COLUMNS:

            if col == "id":
                continue

            if col in data:
                allowed_updates[col] = str(data.get(col, ""))

        allowed_updates["verified"] = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        update(
            "data_operations",
            allowed_updates,
            "id = ?",
            [row_id]
        )

        return jsonify({
            "status": "success"
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })


# @app.route(
#     "/run-query",
#     methods=["POST"]
# )
# @login_required
# def run_query():

#     try:

#         query = request.json.get(
#             "query"
#         )

#         df = get_sheet_data()

#         result = sqldf(
#             query,
#             {
#                 "data": df
#             }
#         )

#         return jsonify({

#             "status":"success",

#             "rows":
#                 result.fillna("")
#                 .to_dict(
#                     orient="records"
#                 )

#         })

#     except Exception as e:

#         return jsonify({

#             "status":"error",

#             "message":str(e)

#         })

@app.route("/run-query", methods=["POST"])
@login_required
def run_query():

    try:

        query = request.json.get("query", "").strip()

        if not query.lower().startswith("select"):

            return jsonify({
                "status": "error",
                "message": "Only SELECT queries are allowed"
            })

        df = pd.DataFrame(
            get_all("data_operations")
        )

        result = sqldf(
            query,
            {
                "data": df,
                "data_operations": df
            }
        )

        return jsonify({
            "status": "success",
            "rows": result.fillna("").to_dict(orient="records")
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })

# @app.route("/verification-stats")
# @login_required
# def verification_stats():

#     df = get_sheet_data()

#     df.columns = (
#         df.columns
#         .str.lower()
#         .str.strip()
#     )

#     today = datetime.now().strftime(
#         "%Y-%m-%d"
#     )

#     df = df.fillna("")

#     maricar = len(
#         df[
#             (df["assign"].str.lower() == "maricar")
#             &
#             (
#                 df["verified"]
#                 .astype(str)
#                 .str.startswith(today)
#             )
#         ]
#     )

#     maureene = len(
#         df[
#             (df["assign"].str.lower() == "maureene")
#             &
#             (
#                 df["verified"]
#                 .astype(str)
#                 .str.startswith(today)
#             )
#         ]
#     )

#     return jsonify({

#         "maricar": maricar,

#         "maureene": maureene

#     })

@app.route("/verification-stats")
@login_required
def verification_stats():

    try:

        today = datetime.now().strftime("%Y-%m-%d")

        rows = get_all("data_operations")

        maricar = 0
        maureene = 0

        for row in rows:

            assign = str(row.get("assign", "")).lower()
            verified = str(row.get("verified", ""))

            if verified.startswith(today):

                if assign == "maricar":
                    maricar += 1

                elif assign == "maureene":
                    maureene += 1

        return jsonify({
            "maricar": maricar,
            "maureene": maureene
        })

    except Exception as e:

        return jsonify({
            "error": str(e)
        })

@app.route("/close-ticket", methods=["POST"])
@login_required
def close_ticket():

    try:

        message_id = str(
            request.json.get("message_id")
        ).strip()

        spreadsheet = gc.open_by_key(
            "1CeJ8hxjkKly6Ef5hW1spb5E37F7ANKPp-Bsud5x8hpM"
        )

        sheet = spreadsheet.worksheet(
            "CustomerMessages"
        )

        all_rows = sheet.get_all_values()

        headers = [
            h.strip().lower()
            for h in all_rows[0]
        ]

        print("HEADERS:", headers)

        message_id_col = headers.index(
            "message_id"
        )

        status_col = headers.index(
            "status"
        )

        last_updated_col = headers.index(
            "last_updated"
        )

        target_row = None

        for row_num, row in enumerate(
            all_rows[1:],
            start=2
        ):

            if len(row) > message_id_col:

                if str(
                    row[message_id_col]
                ).strip() == message_id:

                    target_row = row_num

                    break

        print(
            "MESSAGE ID:",
            message_id
        )

        print(
            "TARGET ROW:",
            target_row
        )

        if target_row is None:

            return jsonify({
                "status": "error",
                "message": "Ticket Not Found"
            })

        sheet.update_cell(
            target_row,
            status_col + 1,
            "Closed"
        )

        sheet.update_cell(
            target_row,
            last_updated_col + 1,
            datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            )
        )

        return jsonify({
            "status": "success"
        })

    except Exception as e:

        print(e)

        return jsonify({
            "status": "error",
            "message": str(e)
        })

@app.route("/communications-v2data")
@login_required
def communications_v2_data():

    try:

        # onboarding = (
        #     get_onboarding_sheet()
        #     .get_all_records()
        # )

        # followups = (
        #     get_followup_sheet()
        #     .get_all_records()
        # )

        onboarding = get_all("onboarding")

        followups = get_all("payment_follow_up")

        # communications = (
        # get_communications_sheet()
        # .get_all_records()
        # ) 

        communications = get_all("communications")

        conversation_lookup = {}

        for msg in communications:

            lead = str(msg.get("lead_id", ""))

            if lead == "":
                continue

            if lead not in conversation_lookup:

                conversation_lookup[lead] = {

                    "last_message": "",

                    "last_message_time": "",

                    "unread_count": 0

                }

            conversation_lookup[lead]["last_message"] = msg.get(
                "message",
                ""
            )

            conversation_lookup[lead]["last_message_time"] = msg.get(
                "created_at",
                ""
            )

            if (
                msg.get("sender", "").lower() == "customer"
                and msg.get("read_status", "").lower() == "unread"
            ):

                conversation_lookup[lead]["unread_count"] += 1  

        customers = []

        #
        # Active Customers
        #

        

        for row in onboarding:

            

            customers.append({

                 "conversation_id":
                    row.get(
                        "conversation_id",
                        ""
                    ),

                "customer_id":
                    row.get(
                        "customer_id",
                        ""
                    ),

                "lead_id":
                    row.get(
                        "lead_id",
                        ""
                    ),

                "company_name":
                    row.get(
                        "company_name",
                        ""
                    ),

                "customer_name":
                    row.get(
                        "contact_person",
                        ""
                    ),

                "email":
                    row.get(
                        "email",
                        ""
                    ),

                "phone":
                    row.get(
                        "phone",
                        ""
                    ),

                "status":
                    row.get(
                        "status",
                        ""
                    ),

                "payment_status":
                    row.get(
                        "payment_stage",
                        ""
                    ),

                "dataset_status":
                    "Completed",

                "assigned_to":
                    row.get(
                        "assigned_to",
                        ""
                    ),

                "source":
                    "Customer",
                "last_message":
                conversation_lookup.get(
                    row.get("lead_id"),
                    {}
                ).get(
                    "last_message",
                    ""
                ),
                                    
                "last_message_time":
                conversation_lookup.get(
                    row.get("lead_id"),
                    {}
                ).get(
                    "last_message_time",
                    ""
                ),  
                "unread_count":
                conversation_lookup.get(
                    row.get("lead_id"),
                    {}
                ).get(
                    "unread_count",
                    0
                ),  
                "avatar": row.get(
                    "company_name",
                    ""
                )[:1].upper()

            })

        #
        # Payment Follow Ups
        #

        for row in followups:

            customers.append({

                 "conversation_id":
                    row.get(
                        "conversation_id",
                        ""
                    ),

                "customer_id":"",
                
                "lead_id":
                    row.get(
                        "lead_id",
                        ""
                    ),

                "company_name":
                    row.get(
                        "company_name",
                        ""
                    ),

                "customer_name":
                    row.get(
                        "contact_person",
                        ""
                    ),

                "email":
                    row.get(
                        "email",
                        ""
                    ),

                "phone":
                    row.get(
                        "phone",
                        ""
                    ),

                "status":
                    row.get(
                        "payment_status",
                        ""
                    ),

                "payment_status":
                    row.get(
                        "payment_status",
                        ""
                    ),

                "dataset_status":
                    "Waiting Payment",

                "assigned_to":
                    row.get(
                        "assigned_to",
                        ""
                    ),

                "source":
                    "Follow Up",
                "last_message": "",
                "last_message_time": "",
                "unread_count": 0,
                "avatar": row.get(
                    "company_name",
                    ""
                )[:1].upper()

            })
        
        def sort_key(c):

            unread = c.get("unread_count", 0)

            try:
                last = datetime.strptime(
                    c.get("last_message_time", ""),
                    "%Y-%m-%d %H:%M:%S"
                )
            except:
                last = datetime.min

            return (

                unread > 0,

                last

            )

        customers.sort(
            key=sort_key,
            reverse=True
        )
       

    

        return jsonify(

            customers

        )

    except Exception as e:

        return jsonify({

            "error":

                str(e)

        })

@app.route("/conversation/<lead_id>")
@login_required
def conversation(lead_id):

    try:

        # sheet = get_communications_sheet()

        # rows = sheet.get_all_records()

        rows = find_by_lead_id_all(
            "communications",
            lead_id
        )

        messages = []

        for row in rows:

            if str(
                row.get(
                    "lead_id",
                    ""
                )
            ) != str(lead_id):

                continue

            messages.append({

                "sender":
                    row.get(
                        "sender",
                        ""
                    ),

                "message":
                    row.get(
                        "message",
                        ""
                    ),

                "created_at":
                    row.get(
                        "created_at",
                        ""
                    )

            })

        return jsonify(

            messages

        )

    except Exception as e:

        return jsonify({

            "error":

                str(e)

        })

@app.route("/send-message", methods=["POST"])
@login_required
def send_message():

    try:

        data = request.json

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        message_id = "MSG" + now.replace("-", "").replace(":", "").replace(" ", "")

        records = find_by_lead_id_all(
            "communications",
            data.get("lead_id", "")
        )

        conversation_id = ""

        if len(records) > 0:
            conversation_id = records[-1].get("conversation_id", "")

        if conversation_id == "":
            conversation_id = "CONV" + datetime.now().strftime("%Y%m%d%H%M%S")

        insert(
            "communications",
            {
                "conversation_id": conversation_id,
                "message_id": message_id,
                "customer_id": data.get("customer_id", ""),
                "lead_id": data.get("lead_id", ""),
                "company_name": data.get("company_name", ""),
                "customer_name": data.get("customer_name", ""),
                "customer_email": data.get("customer_email", ""),
                "customer_phone": data.get("customer_phone", ""),
                "sender": "Agent",
                "message_type": "Manual",
                "subject": "",
                "message": data.get("message", ""),
                "attachment": "",
                "status": "Open",
                "priority": "Medium",
                "assigned_to": session.get("username", "Admin"),
                "source": "Dashboard",
                "created_at": now,
                "read_status": "Read",
                "replied_at": "",
                "action_required": "",
                "payment_status": data.get("payment_status", ""),
                "dataset_status": data.get("dataset_status", "")
            }
        )

        customer_ai_sheet = get_customer_ai_sheet()

        ai_rows = customer_ai_sheet.get_all_records()

        for i, row in enumerate(ai_rows, start=2):

            if row.get("customer_id") == data.get("customer_id"):

                row["conversation_state"] = "Open"
                row["waiting_for"] = "AI"

                customer_ai_sheet.update(
                    f"A{i}:M{i}",
                    [[
                        row["customer_id"],
                        row["enabled"],
                        row["personality"],
                        row["customer_role"],
                        row["goal"],
                        row["conversation_state"],
                        row["waiting_for"],
                        row["message_count"],
                        row["last_ai_reply"],
                        row["next_reply_after"],
                        row["reply_probability"],
                        row["max_messages"],
                        row["memory_summary"]
                    ]]
                )

                break

        return jsonify({
            "status": "success",
            "created_at": now
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })
    
@app.route("/communications-dashboard")
@login_required
def communications_dashboard():

    today = datetime.now().date()
    yesterday = today - timedelta(days=1)

    today_messages = 0
    yesterday_messages = 0

    today_conversations = set()
    yesterday_conversations = set()

    today_resolved = 0
    yesterday_resolved = 0

    try:

        # sheet = get_communications_sheet()

        # rows = sheet.get_all_records()

        rows = get_all("communications")

        conversation_ids = set()

        messages_sent = 0

        resolved = 0

        last_sender = {}

        for row in rows:

            created_at = row.get("created_at", "")

            row_date = None

            try:
                row_date = datetime.strptime(
                    created_at,
                    "%Y-%m-%d %H:%M:%S"
                ).date()
            except:
                pass

            conversation_id = row.get(
                "conversation_id",
                ""
            )

            sender = (
                row.get(
                    "sender",
                    ""
                )
                .strip()
                .lower()
            )

            status = (
                row.get(
                    "status",
                    ""
                )
                .strip()
                .lower()
            )

            if conversation_id:

                conversation_ids.add(
                    conversation_id
                )

                if row_date == today:
                    today_conversations.add(conversation_id)

                elif row_date == yesterday:
                    yesterday_conversations.add(conversation_id)

                last_sender[
                    conversation_id
                ] = sender

            if sender in [
                "agent",
                "admin",
                "system",
                "bytedata"
            ]:

                messages_sent += 1

                if row_date == today:
                    today_messages += 1

                elif row_date == yesterday:
                    yesterday_messages += 1

            if status in [
                "resolved",
                "closed"
            ]:

                resolved += 1

                if row_date == today:
                    today_resolved += 1

                elif row_date == yesterday:
                    yesterday_resolved += 1

        awaiting = sum(

            1

            for sender in

            last_sender.values()

            if sender in [

                "agent",

                "admin",

                "system",

                "bytedata"

            ]

        )

        def percent_change(today_value, yesterday_value):

            if yesterday_value == 0:

                if today_value == 0:
                    return 0

                return 100

            return round(
                ((today_value - yesterday_value) / yesterday_value) * 100,
                1
            )

        return jsonify({

    "total_conversations": len(conversation_ids),

    "conversation_change":
        percent_change(
            len(today_conversations),
            len(yesterday_conversations)
        ),

    "messages_sent": messages_sent,

    "messages_change":
        percent_change(
            today_messages,
            yesterday_messages
        ),

    "awaiting_response": awaiting,

    "resolved": resolved,

    "resolved_change":
        percent_change(
            today_resolved,
            yesterday_resolved
        ),
    "today_messages":today_messages,

    "today_change":

        percent_change(

            today_messages,

            yesterday_messages

        )

})

    except Exception as e:

        return jsonify({

            "error":

                str(e)

        })
    

@app.route("/current-user")
@login_required
def current_user():

    username = session.get("username", "")

    role = session.get("role", "")

    avatar = username[:1].upper() if username else "?"

    return jsonify({

        "name": username,

        "role": role,

        "avatar": avatar

    })

# @app.route("/mark-conversation-read/<lead_id>", methods=["POST"])
# @login_required
# def mark_conversation_read(lead_id):

#     sheet = get_communications_sheet()

#     records = sheet.get_all_records()

#     for i, row in enumerate(records, start=2):

#         if (
#             str(row.get("lead_id")) == str(lead_id)
#             and row.get("sender", "").lower() == "customer"
#             and row.get("read_status", "").lower() == "unread"
#         ):

#             sheet.update_cell(i, 19, "Read")

#     return jsonify({"success": True})

@app.route("/mark-conversation-read/<lead_id>", methods=["POST"])
@login_required
def mark_conversation_read(lead_id):

    mark_messages_read_by_lead_id(
        lead_id
    )

    return jsonify({"success": True})


@app.route("/resolve-conversation", methods=["POST"])
@login_required
def resolve_conversation():

    try:

        data = request.json

        customer_id = data.get("customer_id", "")
        lead_id = data.get("lead_id", "")

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        #
        # Update Communications status
        #

        # communication_sheet = get_communications_sheet()
        # communication_rows = communication_sheet.get_all_records()

        # for i, row in enumerate(communication_rows, start=2):

        #     if str(row.get("lead_id", "")) == str(lead_id):

        #         row["status"] = "Resolved"
        #         row["replied_at"] = now
        #         row["action_required"] = "No"

        #         communication_sheet.update(
        #             f"A{i}:W{i}",
        #             [[
        #                 row.get("conversation_id", ""),
        #                 row.get("message_id", ""),
        #                 row.get("customer_id", ""),
        #                 row.get("lead_id", ""),
        #                 row.get("company_name", ""),
        #                 row.get("customer_name", ""),
        #                 row.get("customer_email", ""),
        #                 row.get("customer_phone", ""),
        #                 row.get("sender", ""),
        #                 row.get("message_type", ""),
        #                 row.get("subject", ""),
        #                 row.get("message", ""),
        #                 row.get("attachment", ""),
        #                 row.get("status", ""),
        #                 row.get("priority", ""),
        #                 row.get("assigned_to", ""),
        #                 row.get("source", ""),
        #                 row.get("created_at", ""),
        #                 row.get("read_status", ""),
        #                 row.get("replied_at", ""),
        #                 row.get("action_required", ""),
        #                 row.get("payment_status", ""),
        #                 row.get("dataset_status", "")
        #             ]]
        #         )

        #
        # Close CustomerAI conversation
        #

        update(
            "communications",
            {
                "status": "Resolved",
                "replied_at": now,
                "action_required": "No"
            },
            "lead_id = ?",
            [str(lead_id)]
        )

        ai_sheet = get_customer_ai_sheet()
        ai_rows = ai_sheet.get_all_records()

        for i, row in enumerate(ai_rows, start=2):

            if str(row.get("customer_id", "")) == str(customer_id):

                row["conversation_state"] = "Closed"
                row["waiting_for"] = "Closed"
                row["next_reply_after"] = ""

                ai_sheet.update(
                    f"A{i}:M{i}",
                    [[
                        row.get("customer_id", ""),
                        row.get("enabled", ""),
                        row.get("personality", ""),
                        row.get("customer_role", ""),
                        row.get("goal", ""),
                        row.get("conversation_state", ""),
                        row.get("waiting_for", ""),
                        row.get("message_count", ""),
                        row.get("last_ai_reply", ""),
                        row.get("next_reply_after", ""),
                        row.get("reply_probability", ""),
                        row.get("max_messages", ""),
                        row.get("memory_summary", "")
                    ]]
                )

                break

        return jsonify({
            "status": "success",
            "message": "Conversation resolved"
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })

@app.route("/create-support-task", methods=["POST"])
@login_required
def create_support_task():

    try:

        data = request.json

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        task_id = "TASK" + datetime.now().strftime("%Y%m%d%H%M%S")

        insert_row(
            "support_tasks",
            SUPPORT_TASKS_COLUMNS,
            {
                "task_id": task_id,
                "conversation_id": data.get("conversation_id", ""),
                "customer_id": data.get("customer_id", ""),
                "lead_id": data.get("lead_id", ""),
                "company_name": data.get("company_name", ""),
                "customer_name": data.get("customer_name", ""),
                "customer_email": data.get("customer_email", ""),
                "assigned_to": data.get("assigned_to", ""),
                "task_title": data.get("task_title", ""),
                "task_description": data.get("task_description", ""),
                "priority": data.get("priority", "Medium"),
                "status": "Open",
                "created_by": session.get("username", "Admin"),
                "created_at": now,
                "due_date": data.get("due_date", ""),
                "resolved_at": "",
                "notes": data.get("notes", "")
            }
        )

        return jsonify({
            "status": "success",
            "task_id": task_id
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })
    
@app.route("/import-data-file", methods=["POST"])
@login_required
def import_data_file():

    try:

        if "file" not in request.files:
            return jsonify({
                "status": "error",
                "message": "No file uploaded"
            })

        file = request.files["file"]

        if file.filename == "":
            return jsonify({
                "status": "error",
                "message": "No file selected"
            })

        upload_folder = "uploads"

        os.makedirs(upload_folder, exist_ok=True)

        filename = secure_filename(file.filename)

        filepath = os.path.join(upload_folder, filename)

        file.save(filepath)

        if filename.lower().endswith(".csv"):

            df = pd.read_csv(filepath)

        elif filename.lower().endswith((".xlsx", ".xls")):

            df = pd.read_excel(filepath)

        else:

            return jsonify({
                "status": "error",
                "message": "Only CSV or Excel supported."
            })

        df.columns = [
            str(c).strip()
            for c in df.columns
        ]

        next_id = get_next_numeric_id("data_operations")

        imported = 0

        for _, row in df.iterrows():

            data = {}

            for col in DATA_OPERATIONS_COLUMNS:

                if col == "id":

                    data[col] = str(next_id)

                # elif col == "assign":

                #     data[col] = ""

                elif col == "verified":

                    data[col] = "secured"

                else:

                    data[col] = str(
                        row.get(col, "")
                    ).strip()

            insert(
                "data_operations",
                data
            )

            imported += 1
            next_id += 1

        return jsonify({

            "status": "success",

            "rows_imported": imported

        })

    except Exception as e:

        return jsonify({

            "status": "error",

            "message": str(e)

        })

# =====================================
# LOGOUT
# =====================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(
        url_for("login_page")
    )

# =====================================
# AUTO OPEN
# =====================================

def open_browser():

    webbrowser.open_new(
        "http://127.0.0.1:5000"
    )

# =====================================
# RUN
# =====================================
if __name__ == "__main__":

    app.run(
        host="127.0.0.1",
        port=5001,
        debug=False
    )